version: 2
updates:
  - package-ecosystem: "uv"
    directory: "/backend-api"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "uv"
    directory: "/engine"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "pip"
    directory: "/security"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5

  - package-ecosystem: "docker"
    directory: "/backend-api"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/engine"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/frontend"
    schedule:
      interval: "monthly"

  - package-ecosystem: "docker"
    directory: "/security"
    schedule:
      interval: "monthly"
